cmake_minimum_required(VERSION 3.16)
project(lab02-sequential-list LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(MSVC)
  add_compile_options(/utf-8)
endif()
add_executable(task01-basic-seqlist src/task01-basic-seqlist/main.cpp)
add_executable(task02-insert-delete-locate src/task02-insert-delete-locate/main.cpp)
add_executable(task03-menu-application src/task03-menu-application/main.cpp)
